apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-ops
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      name: web
      targetPort: 3000
      nodePort: 32597
  selector:
    app: grafana
